packages:
  - '**'
allowBuilds:
  '@swc/core': set this to true or false
  sharp: set this to true or false
# 1 week (in minutes)
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@archival-iiif/*'
